//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Yakro_2018_uwp_light.Model
{
    public class Category : EntityCore
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual IEnumerable<Event> Event
	{
		get;
		set;
	}

}   
}

