//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Yakro_2018_uwp_light.Model
{
    public class EntityCore
    {
        public virtual object CreatedDate
        {
            get;
            set;
        }

        public virtual object UpadatedDate
        {
            get;
            set;
        }

        public virtual object LogicDeletedDate
        {
            get;
            set;
        }

    }
}

