//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Yakro_2018_uwp_light.Model
{
    public class Event : EntityCore
    {
        public int Id
        {
            get;
            set;
        }

        public string Description
        {
            get;
            set;
        }

        public string ImageUrl
        {
            get;
            set;
        }

        public string Latitude
        {
            get;
            set;
        }

        public string Longitude
        {
            get;
            set;
        }

        public DateTime PublishDate
        {
            get;
            set;
        }

        public int LikeCount
        {
            get;
            set;
        }

        public int DislikeCount
        {
            get;
            set;
        }

        public IEnumerable<EventTags> EventTags
        {
            get;
            set;
        }

        public int CategoryId
        {
            get;
            set;
        }

        public int UserId
        {
            get;
            set;
        }

        public int CountryId
        {
            get;
            set;
        }

        public Category Category
        {
            get;
            set;
        }

        public User User
        {
            get;
            set;
        }

        public Country Country
        {
            get;
            set;
        }

    }
}

